INCIDENTS = {
    "task_easy_payment_timeout": {
        "difficulty": "easy",
        "alert": "ALERT: payment-api p99 latency > 5s for 10 minutes. Error rate 15%.",
        "ground_truth_root_cause": "database_connection_pool_exhausted",
        "ground_truth_runbook": "runbook_db_pool_scale",
        "tool_responses": {
            "logs:payment-api:5m": "ERROR: DB connection timeout after 30s. Pool size: 10/10 in use. Waiting threads: 47.",
            "metrics:payment-api:5m": "db_pool_wait_time p99=28s, active_connections=10, max_connections=10, queue_depth=47",
            "traces:payment-api:5m": "95% of request latency in db.query() awaiting connection from pool",
            "topology:payment-api:5m": "payment-api -> postgres-primary (pool_size=10, max_overflow=0, timeout=30s)",
        },
        "runbooks": {
            "runbook_db_pool_scale": "Increases DB connection pool size to 50 and restarts payment-api",
            "runbook_cache_flush": "Flushes Redis cache layer for payment-api",
            "runbook_rollback_deploy": "Rolls back last deployment of payment-api",
            "runbook_restart_inventory": "Graceful restart of inventory-service",
        },
        "relevant_tool_keys": ["logs:payment-api:5m", "metrics:payment-api:5m"],
    },
    "task_medium_checkout_cascade": {
        "difficulty": "medium",
        "alert": "ALERT: checkout-service error rate 40%. Multiple downstream failures detected.",
        "ground_truth_root_cause": "inventory_service_memory_leak",
        "ground_truth_runbook": "runbook_restart_inventory",
        "tool_responses": {
            "logs:checkout-service:5m": "ERROR: inventory-service call timeout. Retrying (3/3 failed). CircuitBreaker: OPEN.",
            "logs:inventory-service:5m": "WARN: GC pause 8s. Heap: 3.9GB/4GB. OOM imminent. Full GC every 30s.",
            "metrics:inventory-service:10m": "heap_usage=98%, gc_pause_ms p99=7800, request_timeout_rate=80%",
            "metrics:checkout-service:5m": "downstream_error_rate=42%, timeout_rate=38%, p99_latency=12s",
            "traces:checkout-service:5m": "98% of request time in inventory.check_stock() RPC call",
            "topology:checkout-service:5m": "checkout-service -> inventory-service -> redis-cache -> postgres-primary",
        },
        "runbooks": {
            "runbook_restart_inventory": "Graceful restart of inventory-service with heap dump captured",
            "runbook_circuit_breaker": "Enable circuit breaker on checkout->inventory path with fallback",
            "runbook_scale_horizontal": "Add 2 more inventory-service replicas",
            "runbook_db_pool_scale": "Increase DB connection pool size",
        },
        "relevant_tool_keys": [
            "logs:checkout-service:5m",
            "logs:inventory-service:5m",
            "metrics:inventory-service:10m",
        ],
    },
    "task_hard_auth_degradation": {
        "difficulty": "hard",
        "alert": "ALERT: 3% increase in user login failures over 30 minutes. Below paging threshold but trending up.",
        "ground_truth_root_cause": "certificate_expiry_partial_rollout",
        "ground_truth_runbook": "runbook_cert_rotation",
        "tool_responses": {
            "logs:auth-service:30m": "WARN: SSL handshake failure 0.3% on pods 3,7. TLS cert on new pods expires in 2d.",
            "logs:api-gateway:30m": "INFO: 503 upstream from auth-pod-3 (6%), auth-pod-7 (8%). Pods 1,2,4,5,6 healthy.",
            "metrics:auth-service:30m": "login_failure_rate: pod-3=8%, pod-7=6%, pod-1=0.3%, pod-2=0.4%, pod-4=0.5%",
            "metrics:auth-service:1h": "Failure spike began 14:32 UTC — matches rolling deploy of pods 3 and 7",
            "traces:auth-service:30m": "100% of failed login traces route exclusively through pods 3 and 7",
            "topology:auth-service:30m": "auth-service (6 pods): pods 3,7 have NEW cert (sha256:abc); pods 1,2,4,5,6 have OLD cert. LB=round-robin.",
            "traces:api-gateway:30m": "api-gateway distributes to all 6 pods round-robin, no session stickiness",
        },
        "runbooks": {
            "runbook_cert_rotation": "Complete TLS cert rotation uniformly across all auth-service pods",
            "runbook_rollback_deploy": "Rollback auth-service to previous deployment (reverts cert change)",
            "runbook_lb_drain": "Drain pods 3 and 7 from load balancer while cert issue resolved",
            "runbook_cache_flush": "Flush Redis session cache",
            "runbook_db_pool_scale": "Increase DB connection pool size",
        },
        "relevant_tool_keys": [
            "logs:auth-service:30m",
            "metrics:auth-service:30m",
            "traces:auth-service:30m",
            "topology:auth-service:30m",
        ],
    },
}
